pipeline {
    agent any 
    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo") {
            steps {
                sh "git clone https://github.com/jenkins-docs/simple-java-maven-app"
            }
        }
        stage("Build") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn clean install"
                    sleep(10)
                }
            }
        }
        stage("Test") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn test"
                }
            }
        }
    }
}