pipeline {
    agent any

    parameters {
        string(defaultValue: "", description: "Deployment Name?", name: "deploymentName")
        choice(choices: ["US-WEST-2A", "US-WEST-2B", "US-WEST-2C"], description: "Which AZ?", name: "azDeploy")
        booleanParam(defaultValue: false, description: "CONFIRM DEPLOYMENT", name: "confirmDeploy")
    }

    stages {
        stage("Deploy"){
            steps {
                echo "String set to ${deploymentName} \n"
                echo "choice set to ${azDeploy} \n"
                echo "bool set to ${confirmDeploy} \n"
            }
        }
    }
}