pipeline {
    agent any

    stages {
        stage("Demo") {
            steps {
                myFunc("Hello from Demo stage!")
                sh """

                
                """
            }
        }
    }
}

def myFunc(String myText, int myNumber) {
    echo "myText is set to: ${myText}"
}