pipeline {
    agent any

    environment {
        def myString = "Hello There"
        def myNumber = 42
        def myBool = true
    }

    stages {
        stage("Demo") {
            steps {
                echo "myString: ${myString}"
                echo "myNumber: ${myNumber}"
                echo "myBool: ${myBool}"
            }
        }
    }
}